2018-04-23 09:49:56,412 ERROR: Exception on /index [POST] [in /home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/ola/Documents/moringa-school-projects/microblog/app/main/routes.py", line 23, in index
    if form.validate_on_submit():
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/wtforms/fields/core.py", line 204, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/wtforms/fields/core.py", line 224, in _run_validation_chain
    validator(form, self)
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/wtforms/validators.py", line 103, in __call__
    message = field.gettext('Field must be between %(min)d and %(max)d characters long.')
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/wtforms/fields/core.py", line 164, in gettext
    return self._translations.gettext(string)
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask_wtf/i18n.py", line 48, in gettext
    t = _get_translations()
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask_wtf/i18n.py", line 40, in _get_translations
    dirname, [get_locale()], domain='wtforms'
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask_babel/__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "/home/ola/Documents/moringa-school-projects/microblog/app/__init__.py", line 87, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAGES'])
NameError: name 'app' is not defined
2018-04-23 09:50:08,257 ERROR: Exception on /index [POST] [in /home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/ola/Documents/moringa-school-projects/microblog/app/main/routes.py", line 23, in index
    if form.validate_on_submit():
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/wtforms/fields/core.py", line 204, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/wtforms/fields/core.py", line 224, in _run_validation_chain
    validator(form, self)
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/wtforms/validators.py", line 103, in __call__
    message = field.gettext('Field must be between %(min)d and %(max)d characters long.')
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/wtforms/fields/core.py", line 164, in gettext
    return self._translations.gettext(string)
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask_wtf/i18n.py", line 48, in gettext
    t = _get_translations()
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask_wtf/i18n.py", line 40, in _get_translations
    dirname, [get_locale()], domain='wtforms'
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask_babel/__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "/home/ola/Documents/moringa-school-projects/microblog/app/__init__.py", line 87, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAGES'])
NameError: name 'app' is not defined
2018-04-23 09:51:15,888 INFO: Microblog startup [in /home/ola/Documents/moringa-school-projects/microblog/app/__init__.py:81]
2018-04-23 09:52:20,697 ERROR: Exception on /index [POST] [in /home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ola/Documents/moringa-school-projects/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/ola/Documents/moringa-school-projects/microblog/app/main/routes.py", line 26, in index
    db.session.add(title)
NameError: name 'title' is not defined
